-- The content of this file is to be executed after the data is imported.

UPDATE beonecalendars SET colorcode='#71719e;', buttonClass='btn-astro', sortOrder=1  WHERE calendarid=(SELECT calendarid from beonecalendartranslations where transname='Astro Olaylar');
UPDATE beonecalendars SET colorcode='#5fc49f;', buttonClass='btn-nature', sortOrder=2 WHERE calendarid=(SELECT calendarid from beonecalendartranslations where transname='Doğa Olayları');
UPDATE beonecalendars SET colorcode='#efa759;', buttonClass='btn-holy', sortOrder=3 WHERE calendarid=(SELECT calendarid from beonecalendartranslations where transname='Kutsal Günler');
UPDATE beonecalendars SET colorcode='#5fc2c4;', buttonClass='btn-international', sortOrder=4 WHERE calendarid=(SELECT calendarid from beonecalendartranslations where transname='Uluslararası Günler');
UPDATE beonecalendars SET colorcode='#df6c4f;', buttonClass='btn-national', sortOrder=5 WHERE calendarid=(SELECT calendarid from beonecalendartranslations where transname='Ulusal Günler');
UPDATE beonecalendars SET colorcode='#f7d752;', buttonClass='btn-independence', sortOrder=6 WHERE calendarid=(SELECT calendarid from beonecalendartranslations where transname='Bağımsızlık Günleri');

UPDATE beonecalendarsubcategories SET calendaricon='A' WHERE subcategoryid=(SELECT subcategoryid from beonecalendarsubcategorytranslations where calendarsubcategorytrans='Eclipses');
UPDATE beonecalendarsubcategories SET calendaricon='B' WHERE subcategoryid=(SELECT subcategoryid from beonecalendarsubcategorytranslations where calendarsubcategorytrans='Equinoxes and Solstices');
UPDATE beonecalendarsubcategories SET calendaricon='C' WHERE subcategoryid=(SELECT subcategoryid from beonecalendarsubcategorytranslations where calendarsubcategorytrans='Meteor Showers');
UPDATE beonecalendarsubcategories SET calendaricon='D' WHERE subcategoryid=(SELECT subcategoryid from beonecalendarsubcategorytranslations where calendarsubcategorytrans='Moon Phases');
UPDATE beonecalendarsubcategories SET calendaricon='E' WHERE subcategoryid=(SELECT subcategoryid from beonecalendarsubcategorytranslations where calendarsubcategorytrans='Rise & Set');
UPDATE beonecalendarsubcategories SET calendaricon='F' WHERE subcategoryid=(SELECT subcategoryid from beonecalendarsubcategorytranslations where calendarsubcategorytrans='Planetary Retrogrades');
UPDATE beonecalendarsubcategories SET calendaricon='G' WHERE subcategoryid=(SELECT subcategoryid from beonecalendarsubcategorytranslations where calendarsubcategorytrans='Stars Whisper');
UPDATE beonecalendarsubcategories SET calendaricon='H' WHERE subcategoryid=(SELECT subcategoryid from beonecalendarsubcategorytranslations where calendarsubcategorytrans='Plants');
UPDATE beonecalendarsubcategories SET calendaricon='I' WHERE subcategoryid=(SELECT subcategoryid from beonecalendarsubcategorytranslations where calendarsubcategorytrans='Animals');
UPDATE beonecalendarsubcategories SET calendaricon='J' WHERE subcategoryid=(SELECT subcategoryid from beonecalendarsubcategorytranslations where calendarsubcategorytrans='Weather & Other');
UPDATE beonecalendarsubcategories SET calendaricon='K' WHERE subcategoryid=(SELECT subcategoryid from beonecalendarsubcategorytranslations where calendarsubcategorytrans='Bahá''í Faith');
UPDATE beonecalendarsubcategories SET calendaricon='L' WHERE subcategoryid=(SELECT subcategoryid from beonecalendarsubcategorytranslations where calendarsubcategorytrans='Buddhism');
UPDATE beonecalendarsubcategories SET calendaricon='M' WHERE subcategoryid=(SELECT subcategoryid from beonecalendarsubcategorytranslations where calendarsubcategorytrans='Christianity (All Denominations)');
UPDATE beonecalendarsubcategories SET calendaricon='N' WHERE subcategoryid=(SELECT subcategoryid from beonecalendarsubcategorytranslations where calendarsubcategorytrans='Hinduism');
UPDATE beonecalendarsubcategories SET calendaricon='O' WHERE subcategoryid=(SELECT subcategoryid from beonecalendarsubcategorytranslations where calendarsubcategorytrans='Islam');
UPDATE beonecalendarsubcategories SET calendaricon='P' WHERE subcategoryid=(SELECT subcategoryid from beonecalendarsubcategorytranslations where calendarsubcategorytrans='Jainism');
UPDATE beonecalendarsubcategories SET calendaricon='Q' WHERE subcategoryid=(SELECT subcategoryid from beonecalendarsubcategorytranslations where calendarsubcategorytrans='Judaism');
UPDATE beonecalendarsubcategories SET calendaricon='R' WHERE subcategoryid=(SELECT subcategoryid from beonecalendarsubcategorytranslations where calendarsubcategorytrans='Paganism');
UPDATE beonecalendarsubcategories SET calendaricon='S' WHERE subcategoryid=(SELECT subcategoryid from beonecalendarsubcategorytranslations where calendarsubcategorytrans='Shinto');
UPDATE beonecalendarsubcategories SET calendaricon='T' WHERE subcategoryid=(SELECT subcategoryid from beonecalendarsubcategorytranslations where calendarsubcategorytrans='Sikhism');
UPDATE beonecalendarsubcategories SET calendaricon='U' WHERE subcategoryid=(SELECT subcategoryid from beonecalendarsubcategorytranslations where calendarsubcategorytrans='Zoroastrianism');
UPDATE beonecalendarsubcategories SET calendaricon='V' WHERE subcategoryid=(SELECT subcategoryid from beonecalendarsubcategorytranslations where calendarsubcategorytrans='United Nations International Days');
UPDATE beonecalendarsubcategories SET calendaricon='W' WHERE subcategoryid=(SELECT subcategoryid from beonecalendarsubcategorytranslations where calendarsubcategorytrans='Other');
UPDATE beonecalendarsubcategories SET calendaricon='X' WHERE subcategoryid=(SELECT subcategoryid from beonecalendarsubcategorytranslations where calendarsubcategorytrans='Turkey');
UPDATE beonecalendarsubcategories SET calendaricon='Y' WHERE calendarid=(SELECT calendarid from beonecalendartranslations where transname='Independence Days');


-- Dummy data for the sub category setting
insert into UserCalendarSubCategories (select u.userid, s.subcategoryid from users u cross join beonecalendarsubcategories s);


-- PlusC message image numbers for SunRise
UPDATE beonecalendareventtranslations set plusctoweb=79 where eventid=(select ev.eventid from beonecalendarevents ev inner join beonecalendareventtranslations tr on tr.eventid=ev.eventid where tr.eventname='Gün Dogumu' and to_char(ev.eventdate,'YYYY-MM-dd')='2016-12-03');
UPDATE beonecalendareventtranslations set plusctoweb=235 where eventid=(select ev.eventid from beonecalendarevents ev inner join beonecalendareventtranslations tr on tr.eventid=ev.eventid where tr.eventname='Gün Dogumu' and to_char(ev.eventdate,'YYYY-MM-dd')='2016-12-04');
UPDATE beonecalendareventtranslations set plusctoweb=215 where eventid=(select ev.eventid from beonecalendarevents ev inner join beonecalendareventtranslations tr on tr.eventid=ev.eventid where tr.eventname='Gün Dogumu' and to_char(ev.eventdate,'YYYY-MM-dd')='2016-12-05');
UPDATE beonecalendareventtranslations set plusctoweb=390 where eventid=(select ev.eventid from beonecalendarevents ev inner join beonecalendareventtranslations tr on tr.eventid=ev.eventid where tr.eventname='Gün Dogumu' and to_char(ev.eventdate,'YYYY-MM-dd')='2016-12-06');
UPDATE beonecalendareventtranslations set plusctoweb=277 where eventid=(select ev.eventid from beonecalendarevents ev inner join beonecalendareventtranslations tr on tr.eventid=ev.eventid where tr.eventname='Gün Dogumu' and to_char(ev.eventdate,'YYYY-MM-dd')='2016-12-07');
UPDATE beonecalendareventtranslations set plusctoweb=276 where eventid=(select ev.eventid from beonecalendarevents ev inner join beonecalendareventtranslations tr on tr.eventid=ev.eventid where tr.eventname='Gün Dogumu' and to_char(ev.eventdate,'YYYY-MM-dd')='2016-12-08');
UPDATE beonecalendareventtranslations set plusctoweb=290 where eventid=(select ev.eventid from beonecalendarevents ev inner join beonecalendareventtranslations tr on tr.eventid=ev.eventid where tr.eventname='Gün Dogumu' and to_char(ev.eventdate,'YYYY-MM-dd')='2016-12-09');
UPDATE beonecalendareventtranslations set plusctoweb=174 where eventid=(select ev.eventid from beonecalendarevents ev inner join beonecalendareventtranslations tr on tr.eventid=ev.eventid where tr.eventname='Gün Dogumu' and to_char(ev.eventdate,'YYYY-MM-dd')='2016-12-10');
UPDATE beonecalendareventtranslations set plusctoweb=292 where eventid=(select ev.eventid from beonecalendarevents ev inner join beonecalendareventtranslations tr on tr.eventid=ev.eventid where tr.eventname='Gün Dogumu' and to_char(ev.eventdate,'YYYY-MM-dd')='2016-12-11');
UPDATE beonecalendareventtranslations set plusctoweb=295 where eventid=(select ev.eventid from beonecalendarevents ev inner join beonecalendareventtranslations tr on tr.eventid=ev.eventid where tr.eventname='Gün Dogumu' and to_char(ev.eventdate,'YYYY-MM-dd')='2016-12-12');
UPDATE beonecalendareventtranslations set plusctoweb=349 where eventid=(select ev.eventid from beonecalendarevents ev inner join beonecalendareventtranslations tr on tr.eventid=ev.eventid where tr.eventname='Gün Dogumu' and to_char(ev.eventdate,'YYYY-MM-dd')='2016-12-13');
UPDATE beonecalendareventtranslations set plusctoweb=116 where eventid=(select ev.eventid from beonecalendarevents ev inner join beonecalendareventtranslations tr on tr.eventid=ev.eventid where tr.eventname='Gün Dogumu' and to_char(ev.eventdate,'YYYY-MM-dd')='2016-12-14');
UPDATE beonecalendareventtranslations set plusctoweb=285 where eventid=(select ev.eventid from beonecalendarevents ev inner join beonecalendareventtranslations tr on tr.eventid=ev.eventid where tr.eventname='Gün Dogumu' and to_char(ev.eventdate,'YYYY-MM-dd')='2016-12-15');
UPDATE beonecalendareventtranslations set plusctoweb=301 where eventid=(select ev.eventid from beonecalendarevents ev inner join beonecalendareventtranslations tr on tr.eventid=ev.eventid where tr.eventname='Gün Dogumu' and to_char(ev.eventdate,'YYYY-MM-dd')='2016-12-16');
UPDATE beonecalendareventtranslations set plusctoweb=360 where eventid=(select ev.eventid from beonecalendarevents ev inner join beonecalendareventtranslations tr on tr.eventid=ev.eventid where tr.eventname='Gün Dogumu' and to_char(ev.eventdate,'YYYY-MM-dd')='2016-12-17');
UPDATE beonecalendareventtranslations set plusctoweb=258 where eventid=(select ev.eventid from beonecalendarevents ev inner join beonecalendareventtranslations tr on tr.eventid=ev.eventid where tr.eventname='Gün Dogumu' and to_char(ev.eventdate,'YYYY-MM-dd')='2016-12-18');
UPDATE beonecalendareventtranslations set plusctoweb=423 where eventid=(select ev.eventid from beonecalendarevents ev inner join beonecalendareventtranslations tr on tr.eventid=ev.eventid where tr.eventname='Gün Dogumu' and to_char(ev.eventdate,'YYYY-MM-dd')='2016-12-21');
UPDATE beonecalendareventtranslations set plusctoweb=399 where eventid=(select ev.eventid from beonecalendarevents ev inner join beonecalendareventtranslations tr on tr.eventid=ev.eventid where tr.eventname='Gün Dogumu' and to_char(ev.eventdate,'YYYY-MM-dd')='2016-12-22');
UPDATE beonecalendareventtranslations set plusctoweb=248 where eventid=(select ev.eventid from beonecalendarevents ev inner join beonecalendareventtranslations tr on tr.eventid=ev.eventid where tr.eventname='Gün Dogumu' and to_char(ev.eventdate,'YYYY-MM-dd')='2016-12-23');
UPDATE beonecalendareventtranslations set plusctoweb=199 where eventid=(select ev.eventid from beonecalendarevents ev inner join beonecalendareventtranslations tr on tr.eventid=ev.eventid where tr.eventname='Gün Dogumu' and to_char(ev.eventdate,'YYYY-MM-dd')='2016-12-24');
UPDATE beonecalendareventtranslations set plusctoweb=328 where eventid=(select ev.eventid from beonecalendarevents ev inner join beonecalendareventtranslations tr on tr.eventid=ev.eventid where tr.eventname='Gün Dogumu' and to_char(ev.eventdate,'YYYY-MM-dd')='2016-12-25');
UPDATE beonecalendareventtranslations set plusctoweb=20 where eventid=(select ev.eventid from beonecalendarevents ev inner join beonecalendareventtranslations tr on tr.eventid=ev.eventid where tr.eventname='Gün Dogumu' and to_char(ev.eventdate,'YYYY-MM-dd')='2016-12-26');
UPDATE beonecalendareventtranslations set plusctoweb=357 where eventid=(select ev.eventid from beonecalendarevents ev inner join beonecalendareventtranslations tr on tr.eventid=ev.eventid where tr.eventname='Gün Dogumu' and to_char(ev.eventdate,'YYYY-MM-dd')='2016-12-27');
UPDATE beonecalendareventtranslations set plusctoweb=314 where eventid=(select ev.eventid from beonecalendarevents ev inner join beonecalendareventtranslations tr on tr.eventid=ev.eventid where tr.eventname='Gün Dogumu' and to_char(ev.eventdate,'YYYY-MM-dd')='2016-12-28');
UPDATE beonecalendareventtranslations set plusctoweb=423 where eventid=(select ev.eventid from beonecalendarevents ev inner join beonecalendareventtranslations tr on tr.eventid=ev.eventid where tr.eventname='Gün Dogumu' and to_char(ev.eventdate,'YYYY-MM-dd')='2016-12-29');
UPDATE beonecalendareventtranslations set plusctoweb=233 where eventid=(select ev.eventid from beonecalendarevents ev inner join beonecalendareventtranslations tr on tr.eventid=ev.eventid where tr.eventname='Gün Dogumu' and to_char(ev.eventdate,'YYYY-MM-dd')='2016-12-30');
UPDATE beonecalendareventtranslations set plusctoweb=293 where eventid=(select ev.eventid from beonecalendarevents ev inner join beonecalendareventtranslations tr on tr.eventid=ev.eventid where tr.eventname='Gün Dogumu' and to_char(ev.eventdate,'YYYY-MM-dd')='2016-12-31');


-- PlusC message image numbers for SunSet
UPDATE beonecalendareventtranslations set plusctoweb=79 where eventid=(select ev.eventid from beonecalendarevents ev inner join beonecalendareventtranslations tr on tr.eventid=ev.eventid where tr.eventname='Gün Batimi' and to_char(ev.eventdate,'YYYY-MM-dd')='2016-12-03');
UPDATE beonecalendareventtranslations set plusctoweb=235 where eventid=(select ev.eventid from beonecalendarevents ev inner join beonecalendareventtranslations tr on tr.eventid=ev.eventid where tr.eventname='Gün Batimi' and to_char(ev.eventdate,'YYYY-MM-dd')='2016-12-04');
UPDATE beonecalendareventtranslations set plusctoweb=215 where eventid=(select ev.eventid from beonecalendarevents ev inner join beonecalendareventtranslations tr on tr.eventid=ev.eventid where tr.eventname='Gün Batimi' and to_char(ev.eventdate,'YYYY-MM-dd')='2016-12-05');
UPDATE beonecalendareventtranslations set plusctoweb=390 where eventid=(select ev.eventid from beonecalendarevents ev inner join beonecalendareventtranslations tr on tr.eventid=ev.eventid where tr.eventname='Gün Batimi' and to_char(ev.eventdate,'YYYY-MM-dd')='2016-12-06');
UPDATE beonecalendareventtranslations set plusctoweb=277 where eventid=(select ev.eventid from beonecalendarevents ev inner join beonecalendareventtranslations tr on tr.eventid=ev.eventid where tr.eventname='Gün Batimi' and to_char(ev.eventdate,'YYYY-MM-dd')='2016-12-07');
UPDATE beonecalendareventtranslations set plusctoweb=276 where eventid=(select ev.eventid from beonecalendarevents ev inner join beonecalendareventtranslations tr on tr.eventid=ev.eventid where tr.eventname='Gün Batimi' and to_char(ev.eventdate,'YYYY-MM-dd')='2016-12-08');
UPDATE beonecalendareventtranslations set plusctoweb=290 where eventid=(select ev.eventid from beonecalendarevents ev inner join beonecalendareventtranslations tr on tr.eventid=ev.eventid where tr.eventname='Gün Batimi' and to_char(ev.eventdate,'YYYY-MM-dd')='2016-12-09');
UPDATE beonecalendareventtranslations set plusctoweb=174 where eventid=(select ev.eventid from beonecalendarevents ev inner join beonecalendareventtranslations tr on tr.eventid=ev.eventid where tr.eventname='Gün Batimi' and to_char(ev.eventdate,'YYYY-MM-dd')='2016-12-10');
UPDATE beonecalendareventtranslations set plusctoweb=292 where eventid=(select ev.eventid from beonecalendarevents ev inner join beonecalendareventtranslations tr on tr.eventid=ev.eventid where tr.eventname='Gün Batimi' and to_char(ev.eventdate,'YYYY-MM-dd')='2016-12-11');
UPDATE beonecalendareventtranslations set plusctoweb=295 where eventid=(select ev.eventid from beonecalendarevents ev inner join beonecalendareventtranslations tr on tr.eventid=ev.eventid where tr.eventname='Gün Batimi' and to_char(ev.eventdate,'YYYY-MM-dd')='2016-12-12');
UPDATE beonecalendareventtranslations set plusctoweb=349 where eventid=(select ev.eventid from beonecalendarevents ev inner join beonecalendareventtranslations tr on tr.eventid=ev.eventid where tr.eventname='Gün Batimi' and to_char(ev.eventdate,'YYYY-MM-dd')='2016-12-13');
UPDATE beonecalendareventtranslations set plusctoweb=116 where eventid=(select ev.eventid from beonecalendarevents ev inner join beonecalendareventtranslations tr on tr.eventid=ev.eventid where tr.eventname='Gün Batimi' and to_char(ev.eventdate,'YYYY-MM-dd')='2016-12-14');
UPDATE beonecalendareventtranslations set plusctoweb=285 where eventid=(select ev.eventid from beonecalendarevents ev inner join beonecalendareventtranslations tr on tr.eventid=ev.eventid where tr.eventname='Gün Batimi' and to_char(ev.eventdate,'YYYY-MM-dd')='2016-12-15');
UPDATE beonecalendareventtranslations set plusctoweb=301 where eventid=(select ev.eventid from beonecalendarevents ev inner join beonecalendareventtranslations tr on tr.eventid=ev.eventid where tr.eventname='Gün Batimi' and to_char(ev.eventdate,'YYYY-MM-dd')='2016-12-16');
UPDATE beonecalendareventtranslations set plusctoweb=360 where eventid=(select ev.eventid from beonecalendarevents ev inner join beonecalendareventtranslations tr on tr.eventid=ev.eventid where tr.eventname='Gün Batimi' and to_char(ev.eventdate,'YYYY-MM-dd')='2016-12-17');
UPDATE beonecalendareventtranslations set plusctoweb=258 where eventid=(select ev.eventid from beonecalendarevents ev inner join beonecalendareventtranslations tr on tr.eventid=ev.eventid where tr.eventname='Gün Batimi' and to_char(ev.eventdate,'YYYY-MM-dd')='2016-12-18');
UPDATE beonecalendareventtranslations set plusctoweb=423 where eventid=(select ev.eventid from beonecalendarevents ev inner join beonecalendareventtranslations tr on tr.eventid=ev.eventid where tr.eventname='Gün Batimi' and to_char(ev.eventdate,'YYYY-MM-dd')='2016-12-21');
UPDATE beonecalendareventtranslations set plusctoweb=399 where eventid=(select ev.eventid from beonecalendarevents ev inner join beonecalendareventtranslations tr on tr.eventid=ev.eventid where tr.eventname='Gün Batimi' and to_char(ev.eventdate,'YYYY-MM-dd')='2016-12-22');
UPDATE beonecalendareventtranslations set plusctoweb=248 where eventid=(select ev.eventid from beonecalendarevents ev inner join beonecalendareventtranslations tr on tr.eventid=ev.eventid where tr.eventname='Gün Batimi' and to_char(ev.eventdate,'YYYY-MM-dd')='2016-12-23');
UPDATE beonecalendareventtranslations set plusctoweb=199 where eventid=(select ev.eventid from beonecalendarevents ev inner join beonecalendareventtranslations tr on tr.eventid=ev.eventid where tr.eventname='Gün Batimi' and to_char(ev.eventdate,'YYYY-MM-dd')='2016-12-24');
UPDATE beonecalendareventtranslations set plusctoweb=328 where eventid=(select ev.eventid from beonecalendarevents ev inner join beonecalendareventtranslations tr on tr.eventid=ev.eventid where tr.eventname='Gün Batimi' and to_char(ev.eventdate,'YYYY-MM-dd')='2016-12-25');
UPDATE beonecalendareventtranslations set plusctoweb=20 where eventid=(select ev.eventid from beonecalendarevents ev inner join beonecalendareventtranslations tr on tr.eventid=ev.eventid where tr.eventname='Gün Batimi' and to_char(ev.eventdate,'YYYY-MM-dd')='2016-12-26');
UPDATE beonecalendareventtranslations set plusctoweb=357 where eventid=(select ev.eventid from beonecalendarevents ev inner join beonecalendareventtranslations tr on tr.eventid=ev.eventid where tr.eventname='Gün Batimi' and to_char(ev.eventdate,'YYYY-MM-dd')='2016-12-27');
UPDATE beonecalendareventtranslations set plusctoweb=314 where eventid=(select ev.eventid from beonecalendarevents ev inner join beonecalendareventtranslations tr on tr.eventid=ev.eventid where tr.eventname='Gün Batimi' and to_char(ev.eventdate,'YYYY-MM-dd')='2016-12-28');
UPDATE beonecalendareventtranslations set plusctoweb=423 where eventid=(select ev.eventid from beonecalendarevents ev inner join beonecalendareventtranslations tr on tr.eventid=ev.eventid where tr.eventname='Gün Batimi' and to_char(ev.eventdate,'YYYY-MM-dd')='2016-12-29');
UPDATE beonecalendareventtranslations set plusctoweb=233 where eventid=(select ev.eventid from beonecalendarevents ev inner join beonecalendareventtranslations tr on tr.eventid=ev.eventid where tr.eventname='Gün Batimi' and to_char(ev.eventdate,'YYYY-MM-dd')='2016-12-30');
UPDATE beonecalendareventtranslations set plusctoweb=293 where eventid=(select ev.eventid from beonecalendarevents ev inner join beonecalendareventtranslations tr on tr.eventid=ev.eventid where tr.eventname='Gün Batimi' and to_char(ev.eventdate,'YYYY-MM-dd')='2016-12-31');
UPDATE beonecalendareventtranslations set plusctoweb=10 where eventid=(select ev.eventid from beonecalendarevents ev inner join beonecalendareventtranslations tr on tr.eventid=ev.eventid where tr.eventname='Gün Batimi' and to_char(ev.eventdate,'YYYY-MM-dd')='2017-01-01');
UPDATE beonecalendareventtranslations set plusctoweb=15 where eventid=(select ev.eventid from beonecalendarevents ev inner join beonecalendareventtranslations tr on tr.eventid=ev.eventid where tr.eventname='Gün Batimi' and to_char(ev.eventdate,'YYYY-MM-dd')='2017-01-02');
UPDATE beonecalendareventtranslations set plusctoweb=14 where eventid=(select ev.eventid from beonecalendarevents ev inner join beonecalendareventtranslations tr on tr.eventid=ev.eventid where tr.eventname='Gün Batimi' and to_char(ev.eventdate,'YYYY-MM-dd')='2017-01-03');
UPDATE beonecalendareventtranslations set plusctoweb=18 where eventid=(select ev.eventid from beonecalendarevents ev inner join beonecalendareventtranslations tr on tr.eventid=ev.eventid where tr.eventname='Gün Batimi' and to_char(ev.eventdate,'YYYY-MM-dd')='2017-01-04');
UPDATE beonecalendareventtranslations set plusctoweb=23 where eventid=(select ev.eventid from beonecalendarevents ev inner join beonecalendareventtranslations tr on tr.eventid=ev.eventid where tr.eventname='Gün Batimi' and to_char(ev.eventdate,'YYYY-MM-dd')='2017-01-05');



