-- The content of this file is to be executed after the data is imported.

UPDATE beonecalendars SET colorcode='#674172;', buttonClass='btn-astro', sortOrder=1  WHERE calendarid=(SELECT calendarid from beonecalendartranslations where transname='Astro Olaylar');
UPDATE beonecalendars SET colorcode='#66CC99;', buttonClass='btn-nature', sortOrder=2 WHERE calendarid=(SELECT calendarid from beonecalendartranslations where transname='Doğa Olayları');
UPDATE beonecalendars SET colorcode='#EB9532;', buttonClass='btn-holy', sortOrder=3 WHERE calendarid=(SELECT calendarid from beonecalendartranslations where transname='Kutsal Günler');
UPDATE beonecalendars SET colorcode='#65CBBB;', buttonClass='btn-international', sortOrder=4 WHERE calendarid=(SELECT calendarid from beonecalendartranslations where transname='Uluslararası Günler');
UPDATE beonecalendars SET colorcode='#E74C3C;', buttonClass='btn-national', sortOrder=5 WHERE calendarid=(SELECT calendarid from beonecalendartranslations where transname='Ulusal Günler');
UPDATE beonecalendars SET colorcode='#3D5B9E;', buttonClass='btn-independence', sortOrder=6 WHERE calendarid=(SELECT calendarid from beonecalendartranslations where transname='Bağımsızlık Günleri');

UPDATE beonecalendarsubcategories SET calendaricon='A' WHERE subcategoryid=(SELECT subcategoryid from beonecalendarsubcategorytranslations where calendarsubcategorytrans='Eclipses');
UPDATE beonecalendarsubcategories SET calendaricon='B' WHERE subcategoryid=(SELECT subcategoryid from beonecalendarsubcategorytranslations where calendarsubcategorytrans='Equinoxes and Solstices');
UPDATE beonecalendarsubcategories SET calendaricon='C' WHERE subcategoryid=(SELECT subcategoryid from beonecalendarsubcategorytranslations where calendarsubcategorytrans='Meteor Showers');
UPDATE beonecalendarsubcategories SET calendaricon='D' WHERE subcategoryid=(SELECT subcategoryid from beonecalendarsubcategorytranslations where calendarsubcategorytrans='Moon Phases');
UPDATE beonecalendarsubcategories SET calendaricon='E' WHERE subcategoryid=(SELECT subcategoryid from beonecalendarsubcategorytranslations where calendarsubcategorytrans='Rise & Set');
UPDATE beonecalendarsubcategories SET calendaricon='F' WHERE subcategoryid=(SELECT subcategoryid from beonecalendarsubcategorytranslations where calendarsubcategorytrans='Planetary Retrogrades');
UPDATE beonecalendarsubcategories SET calendaricon='G' WHERE subcategoryid=(SELECT subcategoryid from beonecalendarsubcategorytranslations where calendarsubcategorytrans='Stars Whisper');
UPDATE beonecalendarsubcategories SET calendaricon='H' WHERE subcategoryid=(SELECT subcategoryid from beonecalendarsubcategorytranslations where calendarsubcategorytrans='Plants');
UPDATE beonecalendarsubcategories SET calendaricon='I' WHERE subcategoryid=(SELECT subcategoryid from beonecalendarsubcategorytranslations where calendarsubcategorytrans='Animals');
UPDATE beonecalendarsubcategories SET calendaricon='J' WHERE subcategoryid=(SELECT subcategoryid from beonecalendarsubcategorytranslations where calendarsubcategorytrans='Weather & Other');
UPDATE beonecalendarsubcategories SET calendaricon='K' WHERE subcategoryid=(SELECT subcategoryid from beonecalendarsubcategorytranslations where calendarsubcategorytrans='Bahá''í Faith');
UPDATE beonecalendarsubcategories SET calendaricon='L' WHERE subcategoryid=(SELECT subcategoryid from beonecalendarsubcategorytranslations where calendarsubcategorytrans='Buddhism');
UPDATE beonecalendarsubcategories SET calendaricon='M' WHERE subcategoryid=(SELECT subcategoryid from beonecalendarsubcategorytranslations where calendarsubcategorytrans='Christianity (All Denominations)');
UPDATE beonecalendarsubcategories SET calendaricon='N' WHERE subcategoryid=(SELECT subcategoryid from beonecalendarsubcategorytranslations where calendarsubcategorytrans='Hinduism');
UPDATE beonecalendarsubcategories SET calendaricon='O' WHERE subcategoryid=(SELECT subcategoryid from beonecalendarsubcategorytranslations where calendarsubcategorytrans='Islam');
UPDATE beonecalendarsubcategories SET calendaricon='P' WHERE subcategoryid=(SELECT subcategoryid from beonecalendarsubcategorytranslations where calendarsubcategorytrans='Jainism');
UPDATE beonecalendarsubcategories SET calendaricon='Q' WHERE subcategoryid=(SELECT subcategoryid from beonecalendarsubcategorytranslations where calendarsubcategorytrans='Judaism');
UPDATE beonecalendarsubcategories SET calendaricon='R' WHERE subcategoryid=(SELECT subcategoryid from beonecalendarsubcategorytranslations where calendarsubcategorytrans='Paganism');
UPDATE beonecalendarsubcategories SET calendaricon='S' WHERE subcategoryid=(SELECT subcategoryid from beonecalendarsubcategorytranslations where calendarsubcategorytrans='Shinto');
UPDATE beonecalendarsubcategories SET calendaricon='T' WHERE subcategoryid=(SELECT subcategoryid from beonecalendarsubcategorytranslations where calendarsubcategorytrans='Sikhism');
UPDATE beonecalendarsubcategories SET calendaricon='U' WHERE subcategoryid=(SELECT subcategoryid from beonecalendarsubcategorytranslations where calendarsubcategorytrans='Zoroastrianism');
UPDATE beonecalendarsubcategories SET calendaricon='V' WHERE subcategoryid=(SELECT subcategoryid from beonecalendarsubcategorytranslations where calendarsubcategorytrans='United Nations International Days');
UPDATE beonecalendarsubcategories SET calendaricon='W' WHERE subcategoryid=(SELECT subcategoryid from beonecalendarsubcategorytranslations where calendarsubcategorytrans='Other');
UPDATE beonecalendarsubcategories SET calendaricon='X' WHERE subcategoryid=(SELECT subcategoryid from beonecalendarsubcategorytranslations where calendarsubcategorytrans='Turkey');
UPDATE beonecalendarsubcategories SET calendaricon='Y' WHERE calendarid=(SELECT calendarid from beonecalendartranslations where transname='Independence Days');


-- Dummy data for the sub category setting
insert into UserCalendarSubCategories (select u.userid, s.subcategoryid from users u cross join beonecalendarsubcategories s);


-- PlusC message image numbers for SunRise
UPDATE beonecalendareventtranslations set designnumber='9', pluscmessagenumber='9.366', plusctoweb='9.366e' where eventid=(select ev.eventid from beonecalendarevents ev inner join beonecalendareventtranslations tr on tr.eventid=ev.eventid where tr.eventname='Gün Doğumu' and to_char(ev.eventdate,'YYYY-MM-dd')='2016-12-03');
UPDATE beonecalendareventtranslations set designnumber='9', pluscmessagenumber='9.367', plusctoweb='9.367e' where eventid=(select ev.eventid from beonecalendarevents ev inner join beonecalendareventtranslations tr on tr.eventid=ev.eventid where tr.eventname='Gün Doğumu' and to_char(ev.eventdate,'YYYY-MM-dd')='2016-12-04');
UPDATE beonecalendareventtranslations set designnumber='9', pluscmessagenumber='9.368', plusctoweb='9.368e' where eventid=(select ev.eventid from beonecalendarevents ev inner join beonecalendareventtranslations tr on tr.eventid=ev.eventid where tr.eventname='Gün Doğumu' and to_char(ev.eventdate,'YYYY-MM-dd')='2016-12-05');
UPDATE beonecalendareventtranslations set designnumber='9', pluscmessagenumber='9.369', plusctoweb='9.369e' where eventid=(select ev.eventid from beonecalendarevents ev inner join beonecalendareventtranslations tr on tr.eventid=ev.eventid where tr.eventname='Gün Doğumu' and to_char(ev.eventdate,'YYYY-MM-dd')='2016-12-06');
UPDATE beonecalendareventtranslations set designnumber='9', pluscmessagenumber='9.370', plusctoweb='9.370e' where eventid=(select ev.eventid from beonecalendarevents ev inner join beonecalendareventtranslations tr on tr.eventid=ev.eventid where tr.eventname='Gün Doğumu' and to_char(ev.eventdate,'YYYY-MM-dd')='2016-12-07');
UPDATE beonecalendareventtranslations set designnumber='9', pluscmessagenumber='9.371', plusctoweb='9.371e' where eventid=(select ev.eventid from beonecalendarevents ev inner join beonecalendareventtranslations tr on tr.eventid=ev.eventid where tr.eventname='Gün Doğumu' and to_char(ev.eventdate,'YYYY-MM-dd')='2016-12-08');
UPDATE beonecalendareventtranslations set designnumber='9', pluscmessagenumber='9.372', plusctoweb='9.372e' where eventid=(select ev.eventid from beonecalendarevents ev inner join beonecalendareventtranslations tr on tr.eventid=ev.eventid where tr.eventname='Gün Doğumu' and to_char(ev.eventdate,'YYYY-MM-dd')='2016-12-09');
UPDATE beonecalendareventtranslations set designnumber='9', pluscmessagenumber='9.373', plusctoweb='9.373e' where eventid=(select ev.eventid from beonecalendarevents ev inner join beonecalendareventtranslations tr on tr.eventid=ev.eventid where tr.eventname='Gün Doğumu' and to_char(ev.eventdate,'YYYY-MM-dd')='2016-12-10');
UPDATE beonecalendareventtranslations set designnumber='9', pluscmessagenumber='9.374', plusctoweb='9.374e' where eventid=(select ev.eventid from beonecalendarevents ev inner join beonecalendareventtranslations tr on tr.eventid=ev.eventid where tr.eventname='Gün Doğumu' and to_char(ev.eventdate,'YYYY-MM-dd')='2016-12-11');
UPDATE beonecalendareventtranslations set designnumber='9', pluscmessagenumber='9.375', plusctoweb='9.375e' where eventid=(select ev.eventid from beonecalendarevents ev inner join beonecalendareventtranslations tr on tr.eventid=ev.eventid where tr.eventname='Gün Doğumu' and to_char(ev.eventdate,'YYYY-MM-dd')='2016-12-12');
UPDATE beonecalendareventtranslations set designnumber='9', pluscmessagenumber='9.376', plusctoweb='9.376e' where eventid=(select ev.eventid from beonecalendarevents ev inner join beonecalendareventtranslations tr on tr.eventid=ev.eventid where tr.eventname='Gün Doğumu' and to_char(ev.eventdate,'YYYY-MM-dd')='2016-12-13');
UPDATE beonecalendareventtranslations set designnumber='9', pluscmessagenumber='9.377', plusctoweb='9.377e' where eventid=(select ev.eventid from beonecalendarevents ev inner join beonecalendareventtranslations tr on tr.eventid=ev.eventid where tr.eventname='Gün Doğumu' and to_char(ev.eventdate,'YYYY-MM-dd')='2016-12-14');
UPDATE beonecalendareventtranslations set designnumber='9', pluscmessagenumber='9.378', plusctoweb='9.378e' where eventid=(select ev.eventid from beonecalendarevents ev inner join beonecalendareventtranslations tr on tr.eventid=ev.eventid where tr.eventname='Gün Doğumu' and to_char(ev.eventdate,'YYYY-MM-dd')='2016-12-15');
UPDATE beonecalendareventtranslations set designnumber='9', pluscmessagenumber='9.379', plusctoweb='9.379e' where eventid=(select ev.eventid from beonecalendarevents ev inner join beonecalendareventtranslations tr on tr.eventid=ev.eventid where tr.eventname='Gün Doğumu' and to_char(ev.eventdate,'YYYY-MM-dd')='2016-12-16');
UPDATE beonecalendareventtranslations set designnumber='9', pluscmessagenumber='9.380', plusctoweb='9.380e' where eventid=(select ev.eventid from beonecalendarevents ev inner join beonecalendareventtranslations tr on tr.eventid=ev.eventid where tr.eventname='Gün Doğumu' and to_char(ev.eventdate,'YYYY-MM-dd')='2016-12-17');
UPDATE beonecalendareventtranslations set designnumber='9', pluscmessagenumber='9.381', plusctoweb='9.381e' where eventid=(select ev.eventid from beonecalendarevents ev inner join beonecalendareventtranslations tr on tr.eventid=ev.eventid where tr.eventname='Gün Doğumu' and to_char(ev.eventdate,'YYYY-MM-dd')='2016-12-18');
UPDATE beonecalendareventtranslations set designnumber='9', pluscmessagenumber='9.382', plusctoweb='9.382e' where eventid=(select ev.eventid from beonecalendarevents ev inner join beonecalendareventtranslations tr on tr.eventid=ev.eventid where tr.eventname='Gün Doğumu' and to_char(ev.eventdate,'YYYY-MM-dd')='2016-12-19');
UPDATE beonecalendareventtranslations set designnumber='9', pluscmessagenumber='9.383', plusctoweb='9.383e' where eventid=(select ev.eventid from beonecalendarevents ev inner join beonecalendareventtranslations tr on tr.eventid=ev.eventid where tr.eventname='Gün Doğumu' and to_char(ev.eventdate,'YYYY-MM-dd')='2016-12-20');
UPDATE beonecalendareventtranslations set designnumber='9', pluscmessagenumber='9.384', plusctoweb='9.384e' where eventid=(select ev.eventid from beonecalendarevents ev inner join beonecalendareventtranslations tr on tr.eventid=ev.eventid where tr.eventname='Gün Doğumu' and to_char(ev.eventdate,'YYYY-MM-dd')='2016-12-21');
UPDATE beonecalendareventtranslations set designnumber='9', pluscmessagenumber='9.385', plusctoweb='9.385e' where eventid=(select ev.eventid from beonecalendarevents ev inner join beonecalendareventtranslations tr on tr.eventid=ev.eventid where tr.eventname='Gün Doğumu' and to_char(ev.eventdate,'YYYY-MM-dd')='2016-12-22');
UPDATE beonecalendareventtranslations set designnumber='9', pluscmessagenumber='9.386', plusctoweb='9.386e' where eventid=(select ev.eventid from beonecalendarevents ev inner join beonecalendareventtranslations tr on tr.eventid=ev.eventid where tr.eventname='Gün Doğumu' and to_char(ev.eventdate,'YYYY-MM-dd')='2016-12-23');
UPDATE beonecalendareventtranslations set designnumber='9', pluscmessagenumber='9.387', plusctoweb='9.387e' where eventid=(select ev.eventid from beonecalendarevents ev inner join beonecalendareventtranslations tr on tr.eventid=ev.eventid where tr.eventname='Gün Doğumu' and to_char(ev.eventdate,'YYYY-MM-dd')='2016-12-24');
UPDATE beonecalendareventtranslations set designnumber='9', pluscmessagenumber='9.388', plusctoweb='9.388e' where eventid=(select ev.eventid from beonecalendarevents ev inner join beonecalendareventtranslations tr on tr.eventid=ev.eventid where tr.eventname='Gün Doğumu' and to_char(ev.eventdate,'YYYY-MM-dd')='2016-12-25');
UPDATE beonecalendareventtranslations set designnumber='9', pluscmessagenumber='9.389', plusctoweb='9.389e' where eventid=(select ev.eventid from beonecalendarevents ev inner join beonecalendareventtranslations tr on tr.eventid=ev.eventid where tr.eventname='Gün Doğumu' and to_char(ev.eventdate,'YYYY-MM-dd')='2016-12-26');
UPDATE beonecalendareventtranslations set designnumber='9', pluscmessagenumber='9.390', plusctoweb='9.390e' where eventid=(select ev.eventid from beonecalendarevents ev inner join beonecalendareventtranslations tr on tr.eventid=ev.eventid where tr.eventname='Gün Doğumu' and to_char(ev.eventdate,'YYYY-MM-dd')='2016-12-27');
UPDATE beonecalendareventtranslations set designnumber='9', pluscmessagenumber='9.391', plusctoweb='9.391e' where eventid=(select ev.eventid from beonecalendarevents ev inner join beonecalendareventtranslations tr on tr.eventid=ev.eventid where tr.eventname='Gün Doğumu' and to_char(ev.eventdate,'YYYY-MM-dd')='2016-12-28');
UPDATE beonecalendareventtranslations set designnumber='9', pluscmessagenumber='9.392', plusctoweb='9.392e' where eventid=(select ev.eventid from beonecalendarevents ev inner join beonecalendareventtranslations tr on tr.eventid=ev.eventid where tr.eventname='Gün Doğumu' and to_char(ev.eventdate,'YYYY-MM-dd')='2016-12-29');
UPDATE beonecalendareventtranslations set designnumber='9', pluscmessagenumber='9.393', plusctoweb='9.393e' where eventid=(select ev.eventid from beonecalendarevents ev inner join beonecalendareventtranslations tr on tr.eventid=ev.eventid where tr.eventname='Gün Doğumu' and to_char(ev.eventdate,'YYYY-MM-dd')='2016-12-30');
UPDATE beonecalendareventtranslations set designnumber='9', pluscmessagenumber='9.394', plusctoweb='9.394e' where eventid=(select ev.eventid from beonecalendarevents ev inner join beonecalendareventtranslations tr on tr.eventid=ev.eventid where tr.eventname='Gün Doğumu' and to_char(ev.eventdate,'YYYY-MM-dd')='2016-12-31');



-- PlusC message image numbers for SunSet
UPDATE beonecalendareventtranslations set designnumber='10', pluscmessagenumber='10.366', plusctoweb='10.366e' where eventid=(select ev.eventid from beonecalendarevents ev inner join beonecalendareventtranslations tr on tr.eventid=ev.eventid where tr.eventname='Gün Batımı' and to_char(ev.eventdate,'YYYY-MM-dd')='2016-12-03');
UPDATE beonecalendareventtranslations set designnumber='10', pluscmessagenumber='10.367', plusctoweb='10.367e' where eventid=(select ev.eventid from beonecalendarevents ev inner join beonecalendareventtranslations tr on tr.eventid=ev.eventid where tr.eventname='Gün Batımı' and to_char(ev.eventdate,'YYYY-MM-dd')='2016-12-04');
UPDATE beonecalendareventtranslations set designnumber='10', pluscmessagenumber='10.368', plusctoweb='10.368e' where eventid=(select ev.eventid from beonecalendarevents ev inner join beonecalendareventtranslations tr on tr.eventid=ev.eventid where tr.eventname='Gün Batımı' and to_char(ev.eventdate,'YYYY-MM-dd')='2016-12-05');
UPDATE beonecalendareventtranslations set designnumber='10', pluscmessagenumber='10.369', plusctoweb='10.369e' where eventid=(select ev.eventid from beonecalendarevents ev inner join beonecalendareventtranslations tr on tr.eventid=ev.eventid where tr.eventname='Gün Batımı' and to_char(ev.eventdate,'YYYY-MM-dd')='2016-12-06');
UPDATE beonecalendareventtranslations set designnumber='10', pluscmessagenumber='10.370', plusctoweb='10.370e' where eventid=(select ev.eventid from beonecalendarevents ev inner join beonecalendareventtranslations tr on tr.eventid=ev.eventid where tr.eventname='Gün Batımı' and to_char(ev.eventdate,'YYYY-MM-dd')='2016-12-07');
UPDATE beonecalendareventtranslations set designnumber='10', pluscmessagenumber='10.371', plusctoweb='10.371e' where eventid=(select ev.eventid from beonecalendarevents ev inner join beonecalendareventtranslations tr on tr.eventid=ev.eventid where tr.eventname='Gün Batımı' and to_char(ev.eventdate,'YYYY-MM-dd')='2016-12-08');
UPDATE beonecalendareventtranslations set designnumber='10', pluscmessagenumber='10.372', plusctoweb='10.372e' where eventid=(select ev.eventid from beonecalendarevents ev inner join beonecalendareventtranslations tr on tr.eventid=ev.eventid where tr.eventname='Gün Batımı' and to_char(ev.eventdate,'YYYY-MM-dd')='2016-12-09');
UPDATE beonecalendareventtranslations set designnumber='10', pluscmessagenumber='10.373', plusctoweb='10.373e' where eventid=(select ev.eventid from beonecalendarevents ev inner join beonecalendareventtranslations tr on tr.eventid=ev.eventid where tr.eventname='Gün Batımı' and to_char(ev.eventdate,'YYYY-MM-dd')='2016-12-10');
UPDATE beonecalendareventtranslations set designnumber='10', pluscmessagenumber='10.374', plusctoweb='10.374e' where eventid=(select ev.eventid from beonecalendarevents ev inner join beonecalendareventtranslations tr on tr.eventid=ev.eventid where tr.eventname='Gün Batımı' and to_char(ev.eventdate,'YYYY-MM-dd')='2016-12-11');
UPDATE beonecalendareventtranslations set designnumber='10', pluscmessagenumber='10.375', plusctoweb='10.375e' where eventid=(select ev.eventid from beonecalendarevents ev inner join beonecalendareventtranslations tr on tr.eventid=ev.eventid where tr.eventname='Gün Batımı' and to_char(ev.eventdate,'YYYY-MM-dd')='2016-12-12');
UPDATE beonecalendareventtranslations set designnumber='10', pluscmessagenumber='10.376', plusctoweb='10.376e' where eventid=(select ev.eventid from beonecalendarevents ev inner join beonecalendareventtranslations tr on tr.eventid=ev.eventid where tr.eventname='Gün Batımı' and to_char(ev.eventdate,'YYYY-MM-dd')='2016-12-13');
UPDATE beonecalendareventtranslations set designnumber='10', pluscmessagenumber='10.377', plusctoweb='10.377e' where eventid=(select ev.eventid from beonecalendarevents ev inner join beonecalendareventtranslations tr on tr.eventid=ev.eventid where tr.eventname='Gün Batımı' and to_char(ev.eventdate,'YYYY-MM-dd')='2016-12-14');
UPDATE beonecalendareventtranslations set designnumber='10', pluscmessagenumber='10.378', plusctoweb='10.378e' where eventid=(select ev.eventid from beonecalendarevents ev inner join beonecalendareventtranslations tr on tr.eventid=ev.eventid where tr.eventname='Gün Batımı' and to_char(ev.eventdate,'YYYY-MM-dd')='2016-12-15');
UPDATE beonecalendareventtranslations set designnumber='10', pluscmessagenumber='10.379', plusctoweb='10.379e' where eventid=(select ev.eventid from beonecalendarevents ev inner join beonecalendareventtranslations tr on tr.eventid=ev.eventid where tr.eventname='Gün Batımı' and to_char(ev.eventdate,'YYYY-MM-dd')='2016-12-16');
UPDATE beonecalendareventtranslations set designnumber='10', pluscmessagenumber='10.380', plusctoweb='10.380e' where eventid=(select ev.eventid from beonecalendarevents ev inner join beonecalendareventtranslations tr on tr.eventid=ev.eventid where tr.eventname='Gün Batımı' and to_char(ev.eventdate,'YYYY-MM-dd')='2016-12-17');
UPDATE beonecalendareventtranslations set designnumber='10', pluscmessagenumber='10.381', plusctoweb='10.381e' where eventid=(select ev.eventid from beonecalendarevents ev inner join beonecalendareventtranslations tr on tr.eventid=ev.eventid where tr.eventname='Gün Batımı' and to_char(ev.eventdate,'YYYY-MM-dd')='2016-12-18');
UPDATE beonecalendareventtranslations set designnumber='10', pluscmessagenumber='10.382', plusctoweb='10.382e' where eventid=(select ev.eventid from beonecalendarevents ev inner join beonecalendareventtranslations tr on tr.eventid=ev.eventid where tr.eventname='Gün Batımı' and to_char(ev.eventdate,'YYYY-MM-dd')='2016-12-19');
UPDATE beonecalendareventtranslations set designnumber='10', pluscmessagenumber='10.383', plusctoweb='10.383e' where eventid=(select ev.eventid from beonecalendarevents ev inner join beonecalendareventtranslations tr on tr.eventid=ev.eventid where tr.eventname='Gün Batımı' and to_char(ev.eventdate,'YYYY-MM-dd')='2016-12-20');
UPDATE beonecalendareventtranslations set designnumber='10', pluscmessagenumber='10.384', plusctoweb='10.384e' where eventid=(select ev.eventid from beonecalendarevents ev inner join beonecalendareventtranslations tr on tr.eventid=ev.eventid where tr.eventname='Gün Batımı' and to_char(ev.eventdate,'YYYY-MM-dd')='2016-12-21');
UPDATE beonecalendareventtranslations set designnumber='10', pluscmessagenumber='10.385', plusctoweb='10.385e' where eventid=(select ev.eventid from beonecalendarevents ev inner join beonecalendareventtranslations tr on tr.eventid=ev.eventid where tr.eventname='Gün Batımı' and to_char(ev.eventdate,'YYYY-MM-dd')='2016-12-22');
UPDATE beonecalendareventtranslations set designnumber='10', pluscmessagenumber='10.386', plusctoweb='10.386e' where eventid=(select ev.eventid from beonecalendarevents ev inner join beonecalendareventtranslations tr on tr.eventid=ev.eventid where tr.eventname='Gün Batımı' and to_char(ev.eventdate,'YYYY-MM-dd')='2016-12-23');
UPDATE beonecalendareventtranslations set designnumber='10', pluscmessagenumber='10.387', plusctoweb='10.387e' where eventid=(select ev.eventid from beonecalendarevents ev inner join beonecalendareventtranslations tr on tr.eventid=ev.eventid where tr.eventname='Gün Batımı' and to_char(ev.eventdate,'YYYY-MM-dd')='2016-12-24');
UPDATE beonecalendareventtranslations set designnumber='10', pluscmessagenumber='10.388', plusctoweb='10.388e' where eventid=(select ev.eventid from beonecalendarevents ev inner join beonecalendareventtranslations tr on tr.eventid=ev.eventid where tr.eventname='Gün Batımı' and to_char(ev.eventdate,'YYYY-MM-dd')='2016-12-25');
UPDATE beonecalendareventtranslations set designnumber='10', pluscmessagenumber='10.389', plusctoweb='10.389e' where eventid=(select ev.eventid from beonecalendarevents ev inner join beonecalendareventtranslations tr on tr.eventid=ev.eventid where tr.eventname='Gün Batımı' and to_char(ev.eventdate,'YYYY-MM-dd')='2016-12-26');
UPDATE beonecalendareventtranslations set designnumber='10', pluscmessagenumber='10.390', plusctoweb='10.390e' where eventid=(select ev.eventid from beonecalendarevents ev inner join beonecalendareventtranslations tr on tr.eventid=ev.eventid where tr.eventname='Gün Batımı' and to_char(ev.eventdate,'YYYY-MM-dd')='2016-12-27');
UPDATE beonecalendareventtranslations set designnumber='10', pluscmessagenumber='10.391', plusctoweb='10.391e' where eventid=(select ev.eventid from beonecalendarevents ev inner join beonecalendareventtranslations tr on tr.eventid=ev.eventid where tr.eventname='Gün Batımı' and to_char(ev.eventdate,'YYYY-MM-dd')='2016-12-28');
UPDATE beonecalendareventtranslations set designnumber='10', pluscmessagenumber='10.392', plusctoweb='10.392e' where eventid=(select ev.eventid from beonecalendarevents ev inner join beonecalendareventtranslations tr on tr.eventid=ev.eventid where tr.eventname='Gün Batımı' and to_char(ev.eventdate,'YYYY-MM-dd')='2016-12-29');
UPDATE beonecalendareventtranslations set designnumber='10', pluscmessagenumber='10.393', plusctoweb='10.393e' where eventid=(select ev.eventid from beonecalendarevents ev inner join beonecalendareventtranslations tr on tr.eventid=ev.eventid where tr.eventname='Gün Batımı' and to_char(ev.eventdate,'YYYY-MM-dd')='2016-12-30');
UPDATE beonecalendareventtranslations set designnumber='10', pluscmessagenumber='10.394', plusctoweb='10.394e' where eventid=(select ev.eventid from beonecalendarevents ev inner join beonecalendareventtranslations tr on tr.eventid=ev.eventid where tr.eventname='Gün Batımı' and to_char(ev.eventdate,'YYYY-MM-dd')='2016-12-31');


