package com.beone.webapp.model;

public enum StatusCode {
	LOGIN_SUCCESSFUL,
	REGISTRATION_SUCCESSFUL,
	LOGIN_FAILED,
	REGISTRATION_FAILED,
	MISSING_MANDATORY_FIELD,
	USER_ALREADY_EXISTS,
	PASSWORD_REPETITION_DOESNT_MATCH, 
	QUESTION_DOES_NOT_EXIST, 
	PROVIDED_QUESTION_TYPE_NOT_VALID, 
	PROVIDED_ANSWER_IS_NOT_VALID, 
	ANSWER_DOES_NOT_MATCH_TO_QUESTION, 
	GIVEN_ID_IS_NOT_NUMBER, 
	ANSWER_DOES_NOT_EXIST, 
	ANSWER_DOES_NOT_BELONG_TO_USER,
}
